version: "3"


services:
  ### PHP ########################################################
  php:
    build: ./docker/php/
    volumes:
      - "./docker/php/fpm/pool.d:/etc/php/8.0/fpm/pool.d"
      - "./docker/php/fpm/php-fpm.conf:/etc/php/8.0/fpm/php-fpm.conf"
      - "./docker/php/fpm/php.ini:/etc/php/8.0/fpm/php.ini"
      - ./:/workspace
      - ${HOME}:/root
    stdin_open: true
    tty: true
